version: 1.0.{build}
image: Visual Studio 2019
before_build:
  - nuget restore
  - dotnet restore
  - dotnet tool install --global Codecov.Tool
build:
  verbosity: quiet
test_script:
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
  - codecov -f "FateGrandCalculator.Test/coverage.cobertura.xml"
