namespace FateGrandOrderPOC.Shared.AtlasAcademy.Json
{
    public class ConstantNiceJson
    {
        public int ATTACK_RATE { get; set; }
        public int ATTACK_RATE_RANDOM_MAX { get; set; }
        public int ATTACK_RATE_RANDOM_MIN { get; set; }
        public int BACKSIDE_CLASS_IMAGE_ID { get; set; }
        public int BACKSIDE_SVT_EQUIP_IMAGE_ID { get; set; }
        public int BACKSIDE_SVT_IMAGE_ID { get; set; }
        public int BATTLE_EFFECT_ID_AVOIDANCE { get; set; }
        public int BATTLE_EFFECT_ID_AVOIDANCE_PIERCE { get; set; }
        public int BATTLE_EFFECT_ID_INVINCIBLE { get; set; }
        public int BATTLE_EFFECT_ID_INVINCIBLE_PIERCE { get; set; }
        public int BATTLE_ITEM_DISP_COLUMN { get; set; }
        public int BP_EXPRESSION { get; set; }
        public int CHAINBONUS_ARTS_RATE { get; set; }
        public int CHAINBONUS_BUSTER_RATE { get; set; }
        public int CHAINBONUS_QUICK { get; set; }
        public int COMMAND_ARTS { get; set; }
        public int COMMAND_BUSTER { get; set; }
        public int COMMAND_CODE_DETACHING_ITEM_ID { get; set; }
        public int COMMAND_QUICK { get; set; }
        public int CRITICAL_ATTACK_RATE { get; set; }
        public int CRITICAL_INDIVIDUALITY { get; set; }
        public int CRITICAL_RATE_PER_STAR { get; set; }
        public int CRITICAL_STAR_RATE { get; set; }
        public int CRITICAL_TD_POINT_RATE { get; set; }
        public int DECK_MAX { get; set; }
        public int ENEMY_ATTACK_RATE_ARTS { get; set; }
        public int ENEMY_ATTACK_RATE_BUSTER { get; set; }
        public int ENEMY_ATTACK_RATE_QUICK { get; set; }
        public int ENEMY_MAX_BATTLE_COUNT { get; set; }
        public int EXTRA_ATTACK_RATE_GRAND { get; set; }
        public int EXTRA_ATTACK_RATE_SINGLE { get; set; }
        public int EXTRA_CRITICAL_RATE { get; set; }
        public int FOLLOWER_LIST_EXPIRE_AT { get; set; }
        public int FOLLOWER_REFRESH_RESET_TIME { get; set; }
        public int FOLLOW_FRIEND_POINT { get; set; }
        public int FRIEND_NUM { get; set; }
        public int FULL_TD_POINT { get; set; }
        public int HEROINE_CHANGECARDVOICE { get; set; }
        public int HYDE_SVT_ID { get; set; }
        public int JEKYLL_SVT_ID { get; set; }
        public int LARGE_SUCCESS_MULT_EXP { get; set; }
        public int LARGE_SUCCESS_RATE { get; set; }
        public int MASHU_CHANGE_QUEST_ID { get; set; }
        public int MASHU_CHANGE_WAR_ID { get; set; }
        public int MASHU_SVT_ID1 { get; set; }
        public int MASHU_SVT_ID2 { get; set; }
        public int MAX_BLACK_LIST_NUM { get; set; }
        public int MAX_COMMAND_SPELL { get; set; }
        public int MAX_DROP_FACTOR { get; set; }
        public int MAX_EVENT_POINT { get; set; }
        public int MAX_EXP_FACTOR { get; set; }
        public int MAX_FRIENDPOINT { get; set; }
        public int MAX_FRIENDSHIP_RANK { get; set; }
        public int MAX_FRIEND_CODE { get; set; }
        public int MAX_FRIEND_HISTORY_NUM { get; set; }
        public int MAX_FRIEND_SHIP_UP_RATIO { get; set; }
        public int MAX_MANA { get; set; }
        public int MAX_NEAR_PRESENT_OFFSET_NUM { get; set; }
        public int MAX_PRESENT_BOX_HISTORY_NUM { get; set; }
        public int MAX_PRESENT_BOX_NUM { get; set; }
        public int MAX_PRESENT_RECEIVE_NUM { get; set; }
        public int MAX_QP { get; set; }
        public int MAX_QP_DROP_UP_RATIO { get; set; }
        public int MAX_QP_FACTOR { get; set; }
        public int MAX_RARE_PRI { get; set; }
        public int MAX_RP { get; set; }
        public int MAX_STONE { get; set; }
        public int MAX_USER_COMMAND_CODE { get; set; }
        public int MAX_USER_EQUIP_EXP_UP_RATIO { get; set; }
        public int MAX_USER_ITEM { get; set; }
        public int MAX_USER_LV { get; set; }
        public int MAX_USER_SVT { get; set; }
        public int MAX_USER_SVT_EQUIP { get; set; }
        public int MAX_USER_SVT_EQUIP_STORAGE { get; set; }
        public int MAX_USER_SVT_STORAGE { get; set; }
        public int MENU_CHANGE { get; set; }
        public int OVER_KILL_NP_RATE { get; set; }
        public int OVER_KILL_STAR_ADD { get; set; }
        public int OVER_KILL_STAR_RATE { get; set; }
        public int STAR_RATE_MAX { get; set; }
        public int STATUS_UP_ADJUST_ATK { get; set; }
        public int STATUS_UP_ADJUST_HP { get; set; }
        public int STATUS_UP_BUFF { get; set; }
        public int SUPER_SUCCESS_MULT_EXP { get; set; }
        public int SUPER_SUCCESS_RATE { get; set; }
        public int SUPPORT_DECK_MAX { get; set; }
        public int TAMAMOCAT_STUN_BUFF_ID { get; set; }
        public int TAMAMOCAT_TREASURE_DEVICE_ID_1 { get; set; }
        public int TAMAMOCAT_TREASURE_DEVICE_ID_2 { get; set; }
        public int TEMPORARY_IGNORE_SLEEP_MODE_FOR_TREASURE_DEVICE_SVT_ID_1 { get; set; }
        public int TEMPORARY_IGNORE_SLEEP_MODE_FOR_TREASURE_DEVICE_SVT_ID_2 { get; set; }
        public int TREASUREDEVICE_ID_MASHU3 { get; set; }
        public int USER_ACT { get; set; }
        public int USER_COST { get; set; }
    }
}
